# Generated by Django 5.1.15 on 2026-05-17 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Номер счёта')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма без НДС')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='НДС')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Выставлен')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], max_length=20, null=True, verbose_name='Способ оплаты')),
                ('workorder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='workorders.workorder', verbose_name='Заказ-наряд')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ('-issued_at',),
            },
        ),
    ]
