# Generated by Django 5.1.15 on 2026-05-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс баллов')),
                ('tier', models.CharField(choices=[('bronze', 'Бронзовый'), ('silver', 'Серебряный'), ('gold', 'Золотой'), ('platinum', 'Платиновый')], default='bronze', max_length=20, verbose_name='Уровень')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Счёт лояльности',
                'verbose_name_plural': 'Счета лояльности',
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма (баллы)')),
                ('reason', models.CharField(max_length=200, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount', verbose_name='Счёт')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.appointment', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Транзакция баллов',
                'verbose_name_plural': 'Транзакции баллов',
                'ordering': ['-created_at'],
            },
        ),
    ]
