# Generated by Django 5.1.15 on 2026-05-17 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=120, verbose_name='Специализация')),
                ('experience_years', models.PositiveIntegerField(default=1, verbose_name='Опыт (лет)')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=4, verbose_name='Рейтинг')),
                ('bio', models.TextField(blank=True, verbose_name='О мастере')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['-rating'],
            },
        ),
    ]
