# Generated by Django 5.1.15 on 2026-05-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Время прихода')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает'), ('being_served', 'Обслуживается'), ('done', 'Готово'), ('cancelled', 'Отменено')], default='waiting', max_length=20, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='clients.client', verbose_name='Клиент')),
                ('preferred_barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_queue_entries', to='staff.barber', verbose_name='Желаемый мастер')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_queue_entries', to='staff.barber', verbose_name='Обслужил')),
            ],
            options={
                'verbose_name': 'Запись в очереди',
                'verbose_name_plural': 'Очередь',
                'ordering': ['joined_at'],
            },
        ),
    ]
