# Generated by Django 5.1.15 on 2026-05-17 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В пути'), ('completed', 'Завершён')], default='planned', max_length=12, verbose_name='Статус')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты доставки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('time_window_start', models.TimeField(blank=True, null=True, verbose_name='Окно с')),
                ('time_window_end', models.TimeField(blank=True, null=True, verbose_name='Окно по')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('delivered', 'Доставлено'), ('failed', 'Не доставлено')], default='pending', max_length=12, verbose_name='Статус')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='intake.intaketicket', verbose_name='Квитанция')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='delivery.deliveryroute', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Задание доставки',
                'verbose_name_plural': 'Задания доставки',
                'ordering': ['order'],
            },
        ),
    ]
