# Generated by Django 5.1.15 on 2026-05-17 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Описание работы')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'Выполняется'), ('done', 'Готово'), ('blocked', 'Заблокировано')], default='pending', max_length=20, verbose_name='Статус')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Норма часов')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Факт часов')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Часовая ставка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('mechanic', models.ForeignKey(blank=True, limit_choices_to={'role': 'mechanic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Механик')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workorders.workorder', verbose_name='Заказ-наряд')),
            ],
            options={
                'verbose_name': 'Сервисная работа',
                'verbose_name_plural': 'Сервисные работы',
                'ordering': ('order', 'created_at'),
            },
        ),
    ]
