# Generated by Django 5.1.15 on 2026-05-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория запчастей',
                'verbose_name_plural': 'Категории запчастей',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='Производитель')),
                ('quantity_in_stock', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('reorder_level', models.PositiveIntegerField(default=5, verbose_name='Точка дозаказа')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная цена')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='parts.partcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Запчасть',
                'verbose_name_plural': 'Запчасти',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ед.')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Использована')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='workorders.workorder', verbose_name='Заказ-наряд')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='parts.sparepart', verbose_name='Запчасть')),
            ],
            options={
                'verbose_name': 'Использование запчасти',
                'verbose_name_plural': 'Использование запчастей',
                'ordering': ('-used_at',),
            },
        ),
    ]
