# Generated by Django 5.1.15 on 2026-05-17 17:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=24, unique=True, verbose_name='Номер квитанции')),
                ('status', models.CharField(choices=[('received', 'Принято'), ('sorting', 'Сортировка'), ('washing', 'Стирка'), ('drying', 'Сушка'), ('ironing', 'Глажка'), ('ready', 'Готово к выдаче'), ('delivered', 'Выдано'), ('cancelled', 'Отменено')], db_index=True, default='received', max_length=20, verbose_name='Статус')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Принято')),
                ('ready_by', models.DateTimeField(blank=True, null=True, verbose_name='Готово к (план)')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Готово (факт)')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Выдано')),
                ('pickup_method', models.CharField(choices=[('in_store', 'Самовывоз'), ('delivery', 'Доставка')], default='in_store', max_length=12, verbose_name='Способ получения')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес доставки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Скидка')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Итого')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Оплачено')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr/', verbose_name='QR код')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_taken', to=settings.AUTH_USER_MODEL, verbose_name='Кассир')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Квитанция',
                'verbose_name_plural': 'Квитанции',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='Цвет')),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='Бренд')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Цена')),
                ('status', models.CharField(choices=[('received', 'Принято'), ('sorting', 'Сортировка'), ('washing', 'Стирка'), ('drying', 'Сушка'), ('ironing', 'Глажка'), ('ready', 'Готово к выдаче'), ('delivered', 'Выдано'), ('cancelled', 'Отменено')], default='received', max_length=20, verbose_name='Статус')),
                ('cloth_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.clothtype', verbose_name='Вид одежды')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.servicetype', verbose_name='Услуга')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='intake.intaketicket', verbose_name='Квитанция')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
            },
        ),
    ]
