# Generated by Django 5.1.15 on 2026-05-17 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Принят'), ('diagnosed', 'Диагностирован'), ('awaiting_parts', 'Ожидание запчастей'), ('in_repair', 'В ремонте'), ('quality_check', 'Контроль качества'), ('completed', 'Готов'), ('delivered', 'Выдан'), ('cancelled', 'Отменён')], default='received', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=10, verbose_name='Приоритет')),
                ('problem_description', models.TextField(verbose_name='Описание проблемы')),
                ('diagnosis_notes', models.TextField(blank=True, verbose_name='Заметки по диагностике')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Предв. стоимость')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итоговая стоимость')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Принят')),
                ('expected_ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемая готовность')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('order_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Номер заказ-наряда')),
                ('mileage_at_intake', models.PositiveIntegerField(default=0, verbose_name='Пробег при приёмке')),
                ('assigned_mechanic', models.ForeignKey(blank=True, limit_choices_to={'role': 'mechanic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный механик')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='vehicles.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Заказ-наряд',
                'verbose_name_plural': 'Заказ-наряды',
                'ordering': ('-received_at',),
            },
        ),
    ]
