# Generated by Django 5.1.15 on 2026-05-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('top', 'Верх'), ('bottom', 'Низ'), ('outerwear', 'Верхняя одежда'), ('bedding', 'Постельное'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Категория')),
                ('default_icon', models.CharField(default='👕', max_length=4, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Вид одежды',
                'verbose_name_plural': 'Виды одежды',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Наименование')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='Код')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид услуги',
                'verbose_name_plural': 'Виды услуг',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('cloth_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.clothtype', verbose_name='Вид одежды')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.servicetype', verbose_name='Вид услуги')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ['cloth_type__name', 'service_type__name'],
                'unique_together': {('cloth_type', 'service_type')},
            },
        ),
    ]
