# Generated by Django 5.1.15 on 2026-05-17 17:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Телефон')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма покупок')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
