# Generated by Django 5.1.15 on 2026-05-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=60, verbose_name='Марка')),
                ('model', models.CharField(max_length=60, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('vin', models.CharField(blank=True, max_length=30, verbose_name='VIN')),
                ('mileage_km', models.PositiveIntegerField(default=0, verbose_name='Пробег (км)')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ('-created_at',),
            },
        ),
    ]
